/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package zad2week15;

/**
 *
 * @author Jelin
 */
public class RestoPanel extends javax.swing.JPanel {

    private double priceUser;

    public double getPriceUser() {
        return priceUser;
    }

    public RestoPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnExit = new javax.swing.JButton();
        btnCalculate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        btnExit.setText("Exit");

        btnCalculate.setText("Calculate");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        jLabel1.setText("Vavedete cena,koqto shte se izpishe s dumi v tekst.Pole:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        double price = Double.parseDouble(txtPrice.getText());
        priceUser = price;
        int firstDigit = priceUser*100;
        String result = "";
        if (firstDigit != 0) {
            result += String.format("Sumata e %d leva ", firstDigit);
        }

        double allNumbers = priceUser * 100;
        double ostatak = allNumbers % 100;

        int preveusDigit = (int) (ostatak % 100);

        String stotinki1 = "";

        switch (preveusDigit) {
            case 1:
                stotinki1 += "1 moneta ot 1 stotinka";
                break;
            case 2:
                stotinki1 += "1 moneta ot 2 stotinki";
                break;
            case 3:
                stotinki1 += "1 moneta ot 2 stotinki i 1 moenta ot 1 st.";
                break;
            case 4:
                stotinki1 += "2 moenti ot 2 st";
                break;
            case 5:
                stotinki1 += "edna moneta ot 5 stotinki";
                break;
            case 6:
                stotinki1 += "3 moneti ot 2 stotinki";
                break;
            case 7:
                stotinki1 += " 3 moneti ot 2 st. i edna ot 1 st";
                break;
            case 8:
                stotinki1 += "4 moneti ot po 2 st";
                break;
            case 9:
                stotinki1 += "4 moneti ot po 2 st i edna ot 1 st.";
                break;
            default:
                stotinki1 += "";
                break;
        }

        double lastTwoDigitMultiPlication = ostatak / 10;

        int lastDigit = (int) (lastTwoDigitMultiPlication % 10);
        String stotinki2 = "";

        switch (lastDigit) {
            case 1:
                stotinki2 += "1 moneta ot 10 stotinki";
                break;
            case 2:
                stotinki2 += "1 moneta ot 20 stotinki";
                break;
            case 3:
                stotinki2 += "1 moneta ot 20 stotinki i 1 moenta ot 10 st.";
                break;
            case 4:
                stotinki2 += "2 moneti ot 20 st";
                break;
            case 5:
                stotinki2 += "edna moneta ot 50 stotinki";
                break;
            case 6:
                stotinki2 += "3 moneti ot 20 stotinki";
                break;
            case 7:
                stotinki2 += " 3 moneti ot 20 st. i edna ot 10 st";
                break;
            case 8:
                stotinki2 += "4 moneti ot po 20 st";
                break;
            case 9:
                stotinki2 += "4 moneti ot po 20 st i edna ot 10 st.";
                break;
            default:
                stotinki2 += "";
                break;
        }
        String resultEnd =result+stotinki1+stotinki2;
        jTextArea1.setText(resultEnd);
    }//GEN-LAST:event_btnCalculateActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables
}
